<?php

/**
 * Implements hook_theme().
 */
function ims_popup_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ims_popup' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--ims-popup',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph__ims_popup().
 */
function ims_popup_preprocess_paragraph__ims_popup(&$variables) {
  // Get the current paragraph entity.
  $paragraph = $variables['paragraph'];

  // Retrieve the field_popup_timer value.
  if ($paragraph->hasField('field_ims_popup_timer')) {
    $popup_timer = $paragraph->get('field_ims_popup_timer')->value;

    // Attach the timer value to the Drupal settings.
    $variables['#attached']['drupalSettings']['ims_popup']['ims_popup_timer'] = $popup_timer;
  }

  // Attach the custom CSS and JS libraries.
  $variables['#attached']['library'][] = 'ims_popup/ims_popup';
}
